version: '3'
services:
  backend:
    container_name: userver-logger-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - 8080
    volumes:
      - ./backend/data:/data
      - ./backend/build:/build
      - ./backend/src:/go/src/github.com/ferdn4ndo/userver-logger-slim/src
    env_file:
      - ./backend/.env
#    command: -config.expand-env -config.file=/etc/loki/config/loki-config.yaml
#    healthcheck:
#      test: ["CMD", "curl", "-s", "-f", "http://userver-loki:3100/"]
#      retries: 6

#  container_monitor:
#    container_name: userver-container-monitor
#    build:
#      context: ./container_monitor
#      dockerfile: Dockerfile
#    volumes:
#      - ./container_monitor/data:/opt/monitor/data
#      - ./container_monitor/scripts:/opt/monitor/scripts
#      - ./log_files:/opt/monitor/logs
#      - /var/run/docker.sock:/var/run/docker.sock
#    env_file:
#      - ./container_monitor/.env

networks:
  default:
    external:
      name: nginx-proxy
